version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker: 
      - image: circleci/python:2.7.17
    steps:
      - checkout
      - run:
          command: python -m unittest it_shanbay
          name: Test

workflows:
  main:
    jobs:
      - build-and-test

