name: "CI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  run:
    name: "tests"
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Unit tests
        run: make test
        
      - name: Build
        run: make clean build package
